# Generated by Django 3.0.2 on 2020-01-28 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='charclass',
            new_name='character_class',
        ),
    ]
