# Generated by Django 3.0.2 on 2020-01-29 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_auto_20200128_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ac_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('armour_class_item', models.CharField(blank=True, max_length=50, null=True)),
                ('ac_bonus', models.IntegerField(blank=True, null=True)),
                ('ac_type', models.CharField(blank=True, max_length=50, null=True)),
                ('ac_checkpenalty', models.IntegerField(blank=True, null=True)),
                ('ac_spellfailure', models.IntegerField(blank=True, null=True)),
                ('ac_weight', models.IntegerField(blank=True, null=True)),
                ('ac_properties', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'ordering': ['armour_class_item', 'ac_bonus', 'ac_type', 'ac_checkpenalty', 'ac_spellfailure', 'ac_weight', 'ac_properties'],
            },
        ),
        migrations.CreateModel(
            name='Craft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('craft', models.CharField(blank=True, max_length=50, null=True)),
                ('craft_mod', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['craft', 'craft_mod'],
            },
        ),
        migrations.CreateModel(
            name='Eighth_Lvl_Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eighth_lvl_spell', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['eighth_lvl_spell'],
            },
        ),
        migrations.CreateModel(
            name='Feat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feat', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['feat'],
            },
        ),
        migrations.CreateModel(
            name='Fifth_Lvl_Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fifth_lvl_spell', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['fifth_lvl_spell'],
            },
        ),
        migrations.CreateModel(
            name='First_Lvl_Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_lvl_spell', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['first_lvl_spell'],
            },
        ),
        migrations.CreateModel(
            name='Fourth_Lvl_Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fourth_lvl_spell', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['fourth_lvl_spell'],
            },
        ),
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=300, null=True)),
                ('item_wt', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['item', 'item_wt'],
            },
        ),
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowledge', models.CharField(blank=True, max_length=50, null=True)),
                ('knowledge_mod', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['knowledge', 'knowledge_mod'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['language'],
            },
        ),
        migrations.CreateModel(
            name='Ninth_Lvl_Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ninth_lvl_spell', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['ninth_lvl_spell'],
            },
        ),
        migrations.CreateModel(
            name='Perform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perform', models.CharField(blank=True, max_length=50, null=True)),
                ('perform_mod', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['perform', 'perform_mod'],
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(blank=True, max_length=50, null=True)),
                ('profession_mod', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['profession', 'profession_mod'],
            },
        ),
        migrations.CreateModel(
            name='Second_Lvl_Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second_lvl_spell', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['second_lvl_spell'],
            },
        ),
        migrations.CreateModel(
            name='Seventh_Lvl_Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seventh_lvl_spell', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['seventh_lvl_spell'],
            },
        ),
        migrations.CreateModel(
            name='Sixth_Lvl_Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sixth_lvl_spell', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['sixth_lvl_spell'],
            },
        ),
        migrations.CreateModel(
            name='Special_Ability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_ability', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['special_ability'],
            },
        ),
        migrations.CreateModel(
            name='Third_Lvl_Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('third_lvl_spell', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['third_lvl_spell'],
            },
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon', models.CharField(blank=True, max_length=50, null=True)),
                ('weapon_attack_bonus', models.IntegerField(blank=True, null=True)),
                ('critical', models.IntegerField(blank=True, null=True)),
                ('weapon_type', models.CharField(blank=True, max_length=50, null=True)),
                ('weapon_range', models.IntegerField(blank=True, null=True)),
                ('ammunition', models.CharField(blank=True, max_length=50, null=True)),
                ('damage', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['weapon', 'weapon_attack_bonus', 'critical', 'weapon_type', 'weapon_range', 'ammunition', 'damage'],
            },
        ),
        migrations.CreateModel(
            name='Zero_Lvl_Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zero_lvl_spell', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['zero_lvl_spell'],
            },
        ),
        migrations.RemoveField(
            model_name='character',
            name='ac_bonus',
        ),
        migrations.RemoveField(
            model_name='character',
            name='ac_checkpenalty',
        ),
        migrations.RemoveField(
            model_name='character',
            name='ac_properties',
        ),
        migrations.RemoveField(
            model_name='character',
            name='ac_spellfailure',
        ),
        migrations.RemoveField(
            model_name='character',
            name='ac_type',
        ),
        migrations.RemoveField(
            model_name='character',
            name='ac_weight',
        ),
        migrations.RemoveField(
            model_name='character',
            name='ammunition',
        ),
        migrations.RemoveField(
            model_name='character',
            name='armour_class_item',
        ),
        migrations.RemoveField(
            model_name='character',
            name='craft_mod',
        ),
        migrations.RemoveField(
            model_name='character',
            name='critical',
        ),
        migrations.RemoveField(
            model_name='character',
            name='damage',
        ),
        migrations.RemoveField(
            model_name='character',
            name='eighth_lvl_spl',
        ),
        migrations.RemoveField(
            model_name='character',
            name='feats',
        ),
        migrations.RemoveField(
            model_name='character',
            name='fifth_lvl_spl',
        ),
        migrations.RemoveField(
            model_name='character',
            name='first_lvl_spl',
        ),
        migrations.RemoveField(
            model_name='character',
            name='fourth_lvl_spl',
        ),
        migrations.RemoveField(
            model_name='character',
            name='item_wt',
        ),
        migrations.RemoveField(
            model_name='character',
            name='knowledge_mod',
        ),
        migrations.RemoveField(
            model_name='character',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='character',
            name='ninth_lvl_spl',
        ),
        migrations.RemoveField(
            model_name='character',
            name='perform_mod',
        ),
        migrations.RemoveField(
            model_name='character',
            name='profession_mod',
        ),
        migrations.RemoveField(
            model_name='character',
            name='second_lvl_spl',
        ),
        migrations.RemoveField(
            model_name='character',
            name='seventh_lvl_spl',
        ),
        migrations.RemoveField(
            model_name='character',
            name='sixth_lvl_spl',
        ),
        migrations.RemoveField(
            model_name='character',
            name='special_abilities',
        ),
        migrations.RemoveField(
            model_name='character',
            name='third_lvl_spl',
        ),
        migrations.RemoveField(
            model_name='character',
            name='weapon_attack_bonus',
        ),
        migrations.RemoveField(
            model_name='character',
            name='weapon_range',
        ),
        migrations.RemoveField(
            model_name='character',
            name='weapon_type',
        ),
        migrations.RemoveField(
            model_name='character',
            name='zero_lvl_spl',
        ),
        migrations.AddField(
            model_name='character',
            name='xp_next_lvl',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='character',
            name='craft',
        ),
        migrations.RemoveField(
            model_name='character',
            name='item',
        ),
        migrations.RemoveField(
            model_name='character',
            name='knowledge',
        ),
        migrations.RemoveField(
            model_name='character',
            name='perform',
        ),
        migrations.RemoveField(
            model_name='character',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='character',
            name='weapon',
        ),
        migrations.AddField(
            model_name='character',
            name='ac_item',
            field=models.ManyToManyField(to='characters.Ac_Item'),
        ),
        migrations.AddField(
            model_name='character',
            name='eighth_lvl_spell',
            field=models.ManyToManyField(to='characters.Eighth_Lvl_Spell'),
        ),
        migrations.AddField(
            model_name='character',
            name='feat',
            field=models.ManyToManyField(to='characters.Feat'),
        ),
        migrations.AddField(
            model_name='character',
            name='fifth_lvl_spell',
            field=models.ManyToManyField(to='characters.Fifth_Lvl_Spell'),
        ),
        migrations.AddField(
            model_name='character',
            name='first_lvl_spell',
            field=models.ManyToManyField(to='characters.First_Lvl_Spell'),
        ),
        migrations.AddField(
            model_name='character',
            name='fourth_lvl_spell',
            field=models.ManyToManyField(to='characters.Fourth_Lvl_Spell'),
        ),
        migrations.AddField(
            model_name='character',
            name='language',
            field=models.ManyToManyField(to='characters.Language'),
        ),
        migrations.AddField(
            model_name='character',
            name='ninth_lvl_spell',
            field=models.ManyToManyField(to='characters.Ninth_Lvl_Spell'),
        ),
        migrations.AddField(
            model_name='character',
            name='second_lvl_spell',
            field=models.ManyToManyField(to='characters.Second_Lvl_Spell'),
        ),
        migrations.AddField(
            model_name='character',
            name='seventh_lvl_spell',
            field=models.ManyToManyField(to='characters.Seventh_Lvl_Spell'),
        ),
        migrations.AddField(
            model_name='character',
            name='sixth_lvl_spell',
            field=models.ManyToManyField(to='characters.Sixth_Lvl_Spell'),
        ),
        migrations.AddField(
            model_name='character',
            name='special_ability',
            field=models.ManyToManyField(to='characters.Special_Ability'),
        ),
        migrations.AddField(
            model_name='character',
            name='third_lvl_spell',
            field=models.ManyToManyField(to='characters.Third_Lvl_Spell'),
        ),
        migrations.AddField(
            model_name='character',
            name='zero_lvl_spell',
            field=models.ManyToManyField(to='characters.Zero_Lvl_Spell'),
        ),
        migrations.AddField(
            model_name='character',
            name='craft',
            field=models.ManyToManyField(to='characters.Craft'),
        ),
        migrations.AddField(
            model_name='character',
            name='item',
            field=models.ManyToManyField(to='characters.Gear'),
        ),
        migrations.AddField(
            model_name='character',
            name='knowledge',
            field=models.ManyToManyField(to='characters.Knowledge'),
        ),
        migrations.AddField(
            model_name='character',
            name='perform',
            field=models.ManyToManyField(to='characters.Perform'),
        ),
        migrations.AddField(
            model_name='character',
            name='profession',
            field=models.ManyToManyField(to='characters.Profession'),
        ),
        migrations.AddField(
            model_name='character',
            name='weapon',
            field=models.ManyToManyField(to='characters.Weapon'),
        ),
    ]
