# Generated by Django 3.0.2 on 2020-01-31 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0007_auto_20200129_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='weight',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
