# Generated by Django 3.0.2 on 2020-01-31 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0008_character_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='critical',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
