# Generated by Django 3.0.2 on 2020-02-03 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0009_auto_20200131_1451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weapon',
            options={'ordering': ['weapon', 'weapon_category', 'weapon_class', 'weapon_price', 'weapon_s_dmg', 'weapon_m_dmg', 'weapon_weight', 'weapon_special', 'weapon_attack_bonus', 'critical', 'weapon_type', 'weapon_range', 'ammunition']},
        ),
        migrations.RenameField(
            model_name='weapon',
            old_name='damage',
            new_name='weapon_m_dmg',
        ),
        migrations.AddField(
            model_name='weapon',
            name='weapon_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='weapon',
            name='weapon_class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='weapon',
            name='weapon_price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='weapon',
            name='weapon_s_dmg',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='weapon',
            name='weapon_special',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='weapon',
            name='weapon_weight',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
