# Generated by Django 3.0.2 on 2020-02-03 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0010_auto_20200202_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='damage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
