# Generated by Django 3.0.2 on 2020-02-03 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0012_remove_weapon_damage'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='lan_speakers',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
