# Generated by Django 3.0.2 on 2020-02-03 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0013_language_lan_speakers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='lan_speakers',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
