# Generated by Django 3.0.2 on 2020-02-03 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0014_auto_20200202_1825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='craft',
            options={'ordering': ['craft']},
        ),
        migrations.RemoveField(
            model_name='craft',
            name='craft_mod',
        ),
        migrations.AddField(
            model_name='character',
            name='craft_mod',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
