# Generated by Django 3.0.2 on 2020-02-03 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0015_auto_20200202_1850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledge',
            options={'ordering': ['knowledge']},
        ),
        migrations.RemoveField(
            model_name='knowledge',
            name='knowledge_mod',
        ),
        migrations.AddField(
            model_name='character',
            name='knowledge_mod',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
