# Generated by Django 3.0.2 on 2020-02-03 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0016_auto_20200202_1852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perform',
            options={'ordering': ['perform']},
        ),
        migrations.RemoveField(
            model_name='perform',
            name='perform_mod',
        ),
        migrations.AddField(
            model_name='character',
            name='perform_mod',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
