# Generated by Django 3.0.2 on 2020-02-03 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0017_auto_20200202_1859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profession',
            options={'ordering': ['profession']},
        ),
        migrations.RemoveField(
            model_name='profession',
            name='profession_mod',
        ),
        migrations.AddField(
            model_name='character',
            name='profession_mod',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
