# Generated by Django 3.0.2 on 2020-02-03 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0018_auto_20200202_1906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ac_item',
            options={'ordering': ['armour_class_item', 'ac_cost', 'ac_speed_b30', 'ac_speed_b20', 'ac_bonus', 'ac_type', 'ac_checkpenalty', 'ac_spellfailure', 'ac_weight', 'ac_properties']},
        ),
        migrations.AddField(
            model_name='ac_item',
            name='ac_cost',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ac_item',
            name='ac_speed_b20',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ac_item',
            name='ac_speed_b30',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
