# Generated by Django 3.0.2 on 2020-02-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0019_auto_20200202_1923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ac_item',
            options={'ordering': ['armour_class_item', 'ac_cost', 'ac_speed_b30', 'ac_speed_b20', 'ac_bonus', 'ac_type', 'ac_checkpenalty', 'ac_spellfailure', 'ac_weight', 'ac_max_dex', 'ac_properties']},
        ),
        migrations.AddField(
            model_name='ac_item',
            name='ac_max_dex',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
