# Generated by Django 3.0.2 on 2020-02-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0023_auto_20200203_1052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feat',
            options={'ordering': ['feat', 'feat_benefit', 'feat_type', 'feat_prerequ', 'feat_normal', 'feat_special']},
        ),
        migrations.AddField(
            model_name='feat',
            name='feat_benefit',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='feat',
            name='feat_normal',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='feat',
            name='feat_prerequ',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feat',
            name='feat_special',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='feat',
            name='feat_type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
