# Generated by Django 3.0.2 on 2020-02-03 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0025_character_alignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='ac_item',
            field=models.ManyToManyField(blank=True, null=True, to='characters.Ac_Item'),
        ),
        migrations.AlterField(
            model_name='character',
            name='craft',
            field=models.ManyToManyField(blank=True, null=True, to='characters.Craft'),
        ),
        migrations.AlterField(
            model_name='character',
            name='eighth_lvl_spell',
            field=models.ManyToManyField(blank=True, null=True, to='characters.Eighth_Lvl_Spell'),
        ),
        migrations.AlterField(
            model_name='character',
            name='feat',
            field=models.ManyToManyField(blank=True, null=True, to='characters.Feat'),
        ),
        migrations.AlterField(
            model_name='character',
            name='fifth_lvl_spell',
            field=models.ManyToManyField(blank=True, null=True, to='characters.Fifth_Lvl_Spell'),
        ),
        migrations.AlterField(
            model_name='character',
            name='first_lvl_spell',
            field=models.ManyToManyField(blank=True, null=True, to='characters.First_Lvl_Spell'),
        ),
        migrations.AlterField(
            model_name='character',
            name='fourth_lvl_spell',
            field=models.ManyToManyField(blank=True, null=True, to='characters.Fourth_Lvl_Spell'),
        ),
        migrations.AlterField(
            model_name='character',
            name='item',
            field=models.ManyToManyField(blank=True, null=True, to='characters.Gear'),
        ),
        migrations.AlterField(
            model_name='character',
            name='knowledge',
            field=models.ManyToManyField(blank=True, null=True, to='characters.Knowledge'),
        ),
        migrations.AlterField(
            model_name='character',
            name='language',
            field=models.ManyToManyField(blank=True, null=True, to='characters.Language'),
        ),
        migrations.AlterField(
            model_name='character',
            name='ninth_lvl_spell',
            field=models.ManyToManyField(blank=True, null=True, to='characters.Ninth_Lvl_Spell'),
        ),
        migrations.AlterField(
            model_name='character',
            name='note',
            field=models.ManyToManyField(blank=True, null=True, to='characters.Note'),
        ),
        migrations.AlterField(
            model_name='character',
            name='perform',
            field=models.ManyToManyField(blank=True, null=True, to='characters.Perform'),
        ),
        migrations.AlterField(
            model_name='character',
            name='profession',
            field=models.ManyToManyField(blank=True, null=True, to='characters.Profession'),
        ),
        migrations.AlterField(
            model_name='character',
            name='second_lvl_spell',
            field=models.ManyToManyField(blank=True, null=True, to='characters.Second_Lvl_Spell'),
        ),
        migrations.AlterField(
            model_name='character',
            name='seventh_lvl_spell',
            field=models.ManyToManyField(blank=True, null=True, to='characters.Seventh_Lvl_Spell'),
        ),
        migrations.AlterField(
            model_name='character',
            name='sixth_lvl_spell',
            field=models.ManyToManyField(blank=True, null=True, to='characters.Sixth_Lvl_Spell'),
        ),
        migrations.AlterField(
            model_name='character',
            name='special_ability',
            field=models.ManyToManyField(blank=True, null=True, to='characters.Special_Ability'),
        ),
        migrations.AlterField(
            model_name='character',
            name='third_lvl_spell',
            field=models.ManyToManyField(blank=True, null=True, to='characters.Third_Lvl_Spell'),
        ),
        migrations.AlterField(
            model_name='character',
            name='weapon',
            field=models.ManyToManyField(blank=True, null=True, to='characters.Weapon'),
        ),
        migrations.AlterField(
            model_name='character',
            name='zero_lvl_spell',
            field=models.ManyToManyField(blank=True, null=True, to='characters.Zero_Lvl_Spell'),
        ),
    ]
