# Generated by Django 3.0.2 on 2020-01-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spell_name', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=100)),
                ('casting_time', models.CharField(max_length=50)),
                ('components', models.CharField(max_length=100)),
                ('spell_range', models.CharField(max_length=100)),
                ('target', models.CharField(max_length=100)),
                ('effect', models.CharField(max_length=100)),
                ('saving_throw', models.CharField(max_length=100)),
                ('spell_resistance', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=400)),
            ],
        ),
    ]
