# Generated by Django 3.0.2 on 2020-01-22 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0002_auto_20200122_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='description',
            field=models.CharField(max_length=1500),
        ),
    ]
