# Generated by Django 3.0.2 on 2020-01-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0005_auto_20200122_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='target',
            field=models.CharField(max_length=300),
        ),
    ]
