# Generated by Django 3.0.2 on 2020-01-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0006_auto_20200128_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='spell_range',
            field=models.CharField(max_length=300),
        ),
    ]
