# Generated by Django 3.0.2 on 2020-01-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0007_auto_20200128_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_name', models.CharField(max_length=50)),
                ('general_description', models.CharField(max_length=5000)),
                ('physical_description', models.CharField(max_length=5000)),
                ('society', models.CharField(max_length=5000)),
                ('relations', models.CharField(max_length=5000)),
                ('alignment_religion', models.CharField(max_length=5000)),
                ('adventurer', models.CharField(max_length=5000)),
                ('male_names', models.CharField(max_length=5000)),
                ('female_names', models.CharField(max_length=5000)),
                ('racial_traits', models.CharField(max_length=5000)),
                ('size', models.CharField(max_length=1000)),
                ('base_speed', models.CharField(max_length=1000)),
                ('vision', models.CharField(max_length=1000)),
                ('special_trait', models.CharField(max_length=5000)),
                ('weapon_familiarity', models.CharField(max_length=5000)),
                ('languages', models.CharField(max_length=5000)),
            ],
        ),
    ]
