from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Character(models.Model):
    player_name = models.ForeignKey(User, on_delete=models.CASCADE)
    character_name = models.CharField(max_length=50)
    char_class = models.CharField(max_length=50)
    diety = models.CharField(max_length=50)
    race = models.CharField(max_length=50)
    homeland = models.CharField(max_length=50)
    size = models.CharField(max_length=50)
    gender = models.CharField(max_length=50)
    age = models.CharField(max_length=50)
    height = models.CharField(max_length=50)
    hair_color = models.CharField(max_length=50)
    eye_color = models.CharField(max_length=50)
    hit_points = models.IntegerField(max_length=6)
    base_speed = models.CharField(max_length=50)
    speed_with_armour = models.IntegerField(max_length=6)
    fly_speed = models.IntegerField(max_length=6)
    swim_speed = models.IntegerField(max_length=6)
    climb_speed = models.IntegerField(max_length=6)
    burrow_speed = models.IntegerField(max_length=6)
    strength = models.IntegerField(max_length=6)
    strength_mod = models.IntegerField(max_length=6)
    dexterity = models.IntegerField(max_length=6)
    dexterity_mod = models.IntegerField(max_length=6)
    constitution = models.IntegerField(max_length=6)
    constitution_mod = models.IntegerField(max_length=6)
    intelligence = models.IntegerField(max_length=6)
    intelligence_mod = models.IntegerField(max_length=6)
    wisdom = models.IntegerField(max_length=6)
    wisdom_mod = models.IntegerField(max_length=6)
    charisma = models.IntegerField(max_length=6)
    charisma_mod = models.IntegerField(max_length=6)
    armor_class = models.IntegerField(max_length=6)
    touch_ac = models.IntegerField(max_length=6)
    flat_footed_ac = models.IntegerField(max_length=6)
    fortitude = models.IntegerField(max_length=6)
    reflex = models.IntegerField(max_length=6)
    will = models.IntegerField(max_length=6)
    base_attack_bonus = models.IntegerField(max_length=6)
    spell_resistance = models.IntegerField(max_length=6)
    cmb = models.IntegerField(max_length=6)
    cmd = models.IntegerField(max_length=6)
    weapon = models.CharField(max_length=50)
    weapon_attack_bonus = models.IntegerField(max_length=6)
    critical = models.IntegerField(max_length=6)
    weapon_type = models.CharField(max_length=50)
    weapon_range = models.IntegerField(max_length=6)
    ammunition = models.CharField(max_length=50)
    damage = models.CharField(max_length=50)
    languages = models.CharField(max_length=1000)
    acrobatics = models.IntegerField(max_length=6)
    appraise = models.IntegerField(max_length=6)
    bluff = models.IntegerField(max_length=6)
    climb = models.IntegerField(max_length=6)
    craft = models.CharField(max_length=50)
    craft_mod = models.IntegerField(max_length=6)
    diplomacy = models.IntegerField(max_length=6)
    disable_device = models.IntegerField(max_length=6)
    disguise = models.IntegerField(max_length=6)
    escape_artist = models.IntegerField(max_length=6)
    fly = models.IntegerField(max_length=6)
    handle_animal = models.IntegerField(max_length=6)
    heal = models.IntegerField(max_length=6)
    intimidate = models.IntegerField(max_length=6)
    knowledge = models.CharField(max_length=50)
    knowledge_mod = models.IntegerField(max_length=6)
    linguistics = models.IntegerField(max_length=6)
    perception = models.IntegerField(max_length=6)
    perform = models.CharField(max_length=50)
    perform_mod = models.IntegerField(max_length=6)
    profession = models.CharField(max_length=50)
    profession_mod = models.IntegerField(max_length=6)
    ride = models.IntegerField(max_length=6)
    sense_motive = models.IntegerField(max_length=6)
    sleight_of_hand = models.IntegerField(max_length=6)
    spellcraft = models.IntegerField(max_length=6)
    stealth = models.IntegerField(max_length=6)
    survival = models.IntegerField(max_length=6)
    swim = models.IntegerField(max_length=6)
    use_magic_device = models.IntegerField(max_length=6)
    armour_class_item = models.CharField(max_length=50)
    ac_bonus = models.IntegerField(max_length=6)
    ac_type = models.CharField(max_length=50)
    ac_checkpenalty = models.IntegerField(max_length=6)
    ac_spellfailure = models.IntegerField(max_length=10)
    ac_weight = models.IntegerField(max_length=6)
    ac_properties = models.CharField(max_length=300)
    item = models.CharField(max_length=300)
    item_wt = models.IntegerField(max_length=6)
    light_load = models.IntegerField(max_length=15)
    medium_load = models.IntegerField(max_length=15)
    heavy_load = models.IntegerField(max_length=15)
    lift_over_head = models.IntegerField(max_length=15)
    lift_off_ground = models.IntegerField(max_length=15)
    drag_or_push = models.IntegerField(max_length=15)
    copper = models.IntegerField(max_length=20)
    silver = models.IntegerField(max_length=20)
    gold = models.IntegerField(max_length=20)
    platinum = models.IntegerField(max_length=20)
    feats = models.CharField(max_length=100)
    special_abilities = models.CharField(max_length=200)
    spells_per_day = models.IntegerField(max_length=6)
    spells_known = models.IntegerField(max_length=6)
    domain_or_speciality_magic = models.CharField(max_length=300)
     






    def __str__(self):
        return f'{self.player_name} {self.character_name}' 